In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/startup_cleaned.csv')
df.head()

,company_brand,sector,stage,amount_usd,what_it_does,year,city
0,thecollegefever,Brand Marketing,seed,3654.0,"TheCollegeFever is a hub for fun, fiesta and f...",2018,Bengaluru
1,happy cow dairy,Agriculture,seed,584710.0,A startup which aggregates milk from dairy far...,2018,Mumbai
2,myloancare,Credit,series a,950153.0,Leading Online Loans Marketplace in India,2018,Gurugram
3,payme india,Financial Services,angel,29235.0,PayMe India is an innovative FinTech organizat...,2018,Noida
4,eunimart,E-Commerce Platforms,seed,NaN,Eunimart is a one stop solution for merchants ...,2018,Hyderabad

In [4]:
df.shape

(2796, 7)

In [5]:
df.columns.tolist()

['company_brand',
 'sector',
 'stage',
 'amount_usd',
 'what_it_does',
 'year',
 'city']

In [6]:
df.isna().sum()

company_brand      0
sector            48
stage            914
amount_usd       540
what_it_does       0
year               0
city             113
dtype: int64

In [7]:
df.dtypes

company_brand     object
sector            object
stage             object
amount_usd       float64
what_it_does      object
year               int64
city              object
dtype: object

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['city'].isna().sum()

np.int64(113)

In [10]:
#standardisizing the city values
#Keep the existing city when a condition is true; otherwise replace it with Python's None as it maps naturally to SQL NULL.
df['city'] = df['city'].where(df['city'].notna(), None)

In [11]:
print(df['city'].isna().sum())

113

In [12]:
#saving the validated dataset
df.to_csv("startups_v1_clean.csv", index=False)

In [13]:
from google.colab import files
files.download('startups_v1_clean.csv')